[package]
name = "grpc-store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "1.2.0"
rustls-pemfile = "2.1.1"
tokio = "1.36.0"
tonic = "0.11.0"
tower = "0.4.13"
tower-http = "0.5.2"
