name: Basic Rust CI
on: [push, pull_request]

jobs:
  cargo-validations:
    name: Rust format check, lint & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install protobuf-compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Format check
        run: cargo fmt --check --all

      - name: Clippy check
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --workspace

  e2e-test:
    name: E2E Docker test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Generate self-signed certificates
        run: make generate_certificates

      - name: Run E2E test
        run: make e2e_test
