name: Basic Rust CI/CD
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy -D warnings
      - run: cargo fmt --check
      - run: cargo test --workspace
