name: Basic Rust CI
on: [push, pull_request]

jobs:
  test:
    name: Rust format check, lint & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install protobuf-compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Format check
        run: cargo fmt --check --all

      - name: Clippy check
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --workspace
