name: Basic Rust CI
on: [push, pull_request]

jobs:
  test:
    name: Rust format check, lint & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check --all
      - run: cargo clippy -- -D warnings
      - run: cargo test --workspace
